### ISSUE TITLE
Disconnected when game is closed

### ISSUE THREAD

**Issue by Debonairesnake6** [TechReborn/RebornStorage#36]
Whenever I close my single player world and re-open it my refined storage machine keeps getting disconnected from my main network and isn't able to view any crafting recipes inside of it. The way I've found to fix this is to break the cable connecting to the multiblock and the rest of my crafters, then after I replace the cable everything works as intended.

**Comment by RogueRaiden** [comment]
Same problem with a server. lags the crap out of the server when reconnected. About 2 1/2 pages of patterns.

**Comment by kz-fox** [comment]
Also affected by this

Versions:
forge-1.10.2-12.18.3.2281
REFINEDSTORAGE-1.2.25
REBORNSTORAGE-1.10.2-1.0.3.30

**Comment by gigabit101** [comment]
Ok so I have been messing with this and the lag is just the size of the multiblock and the amount of slots in the crafter for now just make the multiblock smaller there will be a fix soon

**Comment by modmuss50** [comment]
Ok, I think I have fixed it, or improved it: https://jenkins.modmuss50.me/job/TeamReborn/job/RebornStorage/job/RebornStorage-1.10.2/lastSuccessfulBuild/artifact/build/libs/RebornStorage-1.10.2-1.0.3.31.jar Can you test with this version and let me know how it goes?

**Comment by kz-fox** [comment]
I'll test it tonight and follow up

**Comment by modmuss50** [comment]
That build there was to try and fix the lagg issues, but it may help out with the other issues as well.

**Comment by kz-fox** [comment]
I can't speak for the lag issues, but this build didn't seem to solve the disconnect issue. Figured I'd try anyway.

**Comment by Debonairesnake6** [comment]
I couldn't test the disconnect issue with the new version because my tps basically drops to 0 when I have my system connected. I couldn't run the /forge tps command to get my actual tps because of the lag.

**Comment by modmuss50** [comment]
All development has moved to 1.12, it should fix now.
